In [95]:
import matplotlib.pyplot as plt
import numpy as np

# Primeros intentos.

La verdad es que ahora vamos a ver primer cómo representar el gato, la primer aproximación es una matriz donde las _X_ serán representadas por $1$ y las _O_ por $-1$. Vamos a pensar que los lugares vacíos son representados por $0$. Así pues, lo que tenemos es lo siguiente:

In [96]:
def crear_tablero():
    """
    Este método construye un tablero
    en forma de matriz cuadrada de
    tamaño 3
    
    Returns
    -------
    numpy.ndarray
        A numpy array with shape (3,3) and
        filled with zeros.
    """
    return np.zeros((3,3))

In [97]:
print('Un tablero vacío:')
print(crear_tablero())

Un tablero vacío:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Ahora, vamos a crear una función para verificar si alguno de los participanes ya ganó.  
Primero vamos a empezar con alguno de los renglones.

In [98]:
def win_linea(tablero,transpuesta=False):
    """
    Este método recibe un talbero y determina si
    hay tres elementos iguales en algún renglón.
    Si se introduce la matriz transpuesta se indica
    y regresa la matriz transpuesta.
    
    Parameters
    ----------
    tablero : numpy.ndarray
        Es un numpy.ndarray de shape (3,3) el cual
        simula un tablero de gato
    transpuesta : bool
        Si se introduce el tablero transpuesto se indica.
    
    Returns
    -------
    estados : dict
        Settings dictionary with keys:
            ``1``
                Indicates if 1 won (`bool`).
            ``-1``
                Indicates if -1 won (`bool`).
            ``"tablero"``
                El mismo tablero que se introduce  (`numpy.ndarray`).
    """
    estados = {1:False,-1:False,'tablero':tablero.T if transpuesta else tablero}
    for i in range(3):
        if np.all(tablero[i,:] == tablero[i,0]) and tablero[i,0] != 0:
            print('Ganó '+str(tablero[i,0]))
            estados[tablero[i,0]] = True
            return estados
    return estados

def win_diagonal(tablero):
    """
    Este método recibe un talbero y determina si
    hay tres elementos iguales en algún renglón.
    Si se introduce la matriz transpuesta se indica
    y regresa la matriz transpuesta.
    
    Parameters
    ----------
    tablero : numpy.ndarray
        Es un numpy.ndarray de shape (3,3) el cual
        simula un tablero de gato
    transpuesta : bool
        Si se introduce el tablero transpuesto se indica.
    
    Returns
    -------
    estados : dict
        Settings dictionary with keys:
            ``1``
                Indicates if 1 won (`bool`).
            ``-1``
                Indicates if -1 won (`bool`).
            ``"tablero"``
                El mismo tablero que se introduce  (`numpy.ndarray`).
    """
    estados = {1:False,-1:False,'tablero':tablero}
    
    if np.all(tablero.diagonal() == tablero.diagonal()[0]) and  tablero.diagonal()[0] != 0:
        print('Ganó '+str(tablero.diagonal()[0]))
        estados[tablero.diagonal()[0]] = True
    elif np.all(np.rot90(tablero).diagonal() == np.rot90(tablero).diagonal()[0]) and np.rot90(tablero).diagonal()[0] != 0:
        print('Ganó '+str(np.rot90(tablero).diagonal()[0]))
        estados[np.rot90(tablero).diagonal()[0]] = True
    return estados

In [100]:
tirada = 1
tablero = crear_tablero()
while True:
    print(tablero)
    coord = input('Dame las coodenadas para tirar').replace(')','').replace('(','').split(',')
    tablero[int(coord[0]),int(coord[1])] = tirada
    if win_linea(tablero)[1] or win_linea(tablero.T,transpuesta=True)[1] or win_diagonal(tablero)[1]:
        print('Ganó 1')
        print(tablero)
        break
    elif win_linea(tablero)[-1] or win_linea(tablero.T,transpuesta=True)[-1] or win_diagonal(tablero)[-1]:
        print('Ganó -1')
        print(tablero)
        break
    else:
        tirada = -1*tirada
        if 0 in tablero.reshape(tablero.size):
            pass
        else:
            print('Empate')
            print(tablero)
            break

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Dame las coodenadas para tirar 1,1


[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


Dame las coodenadas para tirar 0,0


[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]


Dame las coodenadas para tirar 0,2


[[-1.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]


Dame las coodenadas para tirar 2,0


[[-1.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]


Dame las coodenadas para tirar 1,0


[[-1.  0.  1.]
 [ 1.  1.  0.]
 [-1.  0.  0.]]


Dame las coodenadas para tirar 1,2


[[-1.  0.  1.]
 [ 1.  1. -1.]
 [-1.  0.  0.]]


Dame las coodenadas para tirar 0,1


[[-1.  1.  1.]
 [ 1.  1. -1.]
 [-1.  0.  0.]]


Dame las coodenadas para tirar 2,2


[[-1.  1.  1.]
 [ 1.  1. -1.]
 [-1.  0. -1.]]


Dame las coodenadas para tirar 2,1


Ganó 1.0
Ganó 1
[[-1.  1.  1.]
 [ 1.  1. -1.]
 [-1.  1. -1.]]
